         # THIS IS MEOW MEOW
# ANA THIS ANOTHER
     .ORG   0
10

     # WOW HOW #COOL THIS CODE IS ?!
# PLEASE STOP COMMENTING

.ORG 10
         INC R0
NOT R1 #INLINE MEOWY COMMENT
# WHOOPS, COMMENT IN THE MIDDLE
# HELP ME, I'M STUCK BETWEEN ASSEMBLY CODE :(
SHL R2,1
SHL R2,1
STD R1,7(R0)
INC R3 #        ANOTHER INLINE# MEOWY COMMENT
INC R4
#LAST COMMENT


LDD R5,7(R0)
#END OF FILE